name             'docker_deploy_test'
maintainer       'TANABE Ken-ichi'
maintainer_email 'nabeken@tknetworks.org'
license          'apache2'
description      'Installs/Configures docker_deploy_test'
long_description 'Installs/Configures docker_deploy_test'
version          '0.2.0'

depends 'deploy'
depends 'docker_deploy'
